services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 60s
      retries: 30

  api-flask:
    image: gastoooon/macave_backend:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./flask/app/:/usr/src/run/
      - ./flask/static/uploads:/usr/src/app/app/static/uploads
      - ./logs:/usr/src/app/logs
    ports:
      - "5001:5001"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
