services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 60s
      retries: 30

  api-flask:
    image: gastoooon/macave_backend:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - FLASK_APP=run.py
    volumes:
      - ./flask/:/usr/src/app/
      - ./flask/static/uploads:/usr/src/app/app/static/uploads
      - ./logs:/usr/src/app/logs
      - ./firebase-adminsdk.json:/usr/src/app/firebase-adminsdk.json
    ports:
      - "5001:5001"
    command: flask run --host=0.0.0.0 --port=5001 --reload

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api-flask
      - adminer

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email gas.duault@gmail.com --agree-tos --no-eff-email
      -d barique.fr -d www.barique.fr"


volumes:
  mysql-data:
