import { createI18n } from "vue-i18n";

const i18n = createI18n({
  locale: 'fr',
  fallbackLocale: 'en',
  messages: {
    fr: {
      connectionError: 'Erreur de connexion',
      addToHisotry: 'ajoutée à l\'historique',
      deleteBottle: 'Erreur de retrait de la bouteille',
      errorLoadBottles: 'Erreur lors du chargement de la cave',
      errorCreateBottle: 'Erreur lors de la création de la bouteille',
      errorUpdateBottle: 'Erreur lors de l\'édition de la bouteille',
      errorLoadCellar: 'Erreur lors du chargement de la liste de cave',
      errorCreateCellar: 'Erreur lors de la création de la cave',
      errorUpdateCellar: 'Erreur lors de l\'édition de la cave',
      errorDeleteCellar: 'Erreur lors de la suppression de la cave',
      editCellar: 'Modifier la Cave',
      newCellar: 'Créer une Cave',
      disconnect: 'Déconnexion',
      changeCellar: 'Changer de cave',
      welcome: 'Bienvenue',
      sign: 'Inscris-toi/ Connecte-toi',
      google: 'avec Google',
      hello: 'Bonjour !',
      your_cellar: 'Vos caves',
      no_cellar: {
        msg_1: "vous n'avez pas de cave pour le moment, vous pouvez en",
        msg_2: "créer",
        msg_3: "une"
      },
      create_cellar: "Création d'une cave",
      cellar_name: "Nom de la cave",
      delete_cellar: {
        warn_1: 'Êtes-vous sûr de vouloir',
        warn_2: 'cette',
      },
      delete: 'supprimer',
      cellar: 'cellar',
      create: 'créer',
      update: 'modifier',
      cancel: 'annuler',
      name_cellar: 'Nom de votre cave',
      search: 'Recherche',
      no_bottle: {
        msg_1: 'votre cave est vide,',
        msg_2: 'vous pouvez ajouter des',
        msg_3: 'bouteilles',
      },
      new_bottle: 'Nouvelle bouteille',
      name: 'Nom',
      cepage: 'Cepage',
      region: 'Région',
      vintage_input: 'Millésime ex : 2016',
      vintage: 'Millésime',
      bottle_drunk: 'Bouteille bue',
      history: 'Historique',
      no_history: {
        msg_1: "Pour le moment votre historique de bouteille bue",
        msg_2: 'est vide'
      },
      image_cellar: "image de la cave",
      bottle_opinion: "Votre avis sur cette bouteille",
      opinion: "Votre avis sur cette bouteille",
      add: "Ajouter",
      aboutTitle: 'A propos de Barique',
      About : {
        firstTest: 'Voici la beta de l\'application Barique.\n' +
          'L\'application est en cours de développement et à sa première version',
        next_features: "Fonctionnalités à venir :",
        features: {
          feature1: "Base données des vins du monde",
          feature2: "Suivres des utilisateurs et partager des vins et caves",
          feature3: "IA sommelier",
        },
      }
    },
    en: {
      connectionError: 'Error of connection',
      addToHisotry: 'added to the history',
      deleteBottle: 'Bottle removal error',
      errorLoadBottles: 'Error when loading the cellar',
      errorCreateBottle: 'Error during bottle creation',
      errorUpdateBottle: 'Error during bottle edition',
      errorLoadCellar: 'Error loading cellar list',
      errorCreateCellar: 'Error during cellar creation',
      errorUpdateCellar: 'Error during cellar edition',
      errorDeleteCellar: 'Error when deleting the cellar',
      editCellar: 'Edit this cellar',
      newCellar: 'New cellar',
      disconnect: 'Disconnect',
      changeCellar: 'Change of cellar',
      welcome: 'Welcome here',
      sign: 'Sign In/ Login',
      google: 'with Google',
      hello: 'Hi !',
      your_cellar: 'Your cellars',
      no_cellar: {
        msg_1: "you don't have a cellar at the moment, you can",
        msg_2: "create",
        msg_3: "one"
      },
      create_cellar: "Creation of a cellar",
      cellar_name: "Nom de la cave",
      delete_cellar: {
        warn_1: 'Are you sure you want to',
        warn_2: 'this',
      },
      delete: 'delete',
      cellar: 'cellar',
      create: 'create',
      update: 'update',
      cancel: 'cancel',
      name_cellar: 'Name of your cellar',
      search: 'Search',
      no_bottle: {
        msg_1: 'For the moment your cellar is empty',
        msg_2: 'you can',
        msg_3: 'Add bottle',
      },
      new_bottle: 'New bottle',
      name: 'Name',
      cepage: 'Cepage',
      region: 'Region',
      vintage_input: 'Vintage ex: 2016',
      vintage: 'Vintage',
      bottle_drunk: 'bottle drunk',
      history: 'History',
      no_history: {
        msg_1: "For the moment your history of bottle drunk",
        msg_2: 'is empty'
      },
    },
    image_cellar: "cellar image",
    bottle_opinion: "Your opinion on this bottle",
    opinion: "Your opinion on this bottle",
    add: "Add",
    aboutTitle: 'About Barique',
    About : {
      firstTest: 'Here\'s the beta of the Barique application.\n' +
        'The application is under development and in its first version. \n',
      features: {
        feature1: 'Database of world wines ',
        feature2: 'Can follow people and share cellar and wine ',
        feature3: 'AI wine steward',
      },
    },
  }
});

export default i18n;