name: Deploy Backend

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull development image, tag as production, and push
        working-directory: ./back
        run: |
          docker pull gastoooon/macave_backend:dev
          docker tag gastoooon/macave_backend:dev gastoooon/macave_backend:latest
          docker push gastoooon/macave_backend:latest

      - name: SSH Create .env
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD
          script: |
            echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > ~/Barique/back/.env
            echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> ~/Barique/back/.env
            echo "MYSQL_USER=${MYSQL_USER}" >> ~/Barique/back/.env
            echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> ~/Barique/back/.env
            echo "FLASK_ENV=production" >> ~/Barique/back/.env
            echo "DOMAIN=${DOMAIN}" >> ~/Barique/back/.env

      - name: Deploy backend with Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd  ~/Barique
            git stash
            git checkout main
            git pull origin main
            cd back
            docker compose -f docker-compose-prod.yml down 
            docker pull gastoooon/macave_backend:latest
            docker compose -f docker-compose-prod.yml up -d --build
