name: Deploy Backend

on:
  pull_request:
    branches:
      - production  
    types:
      - closed
  push:
    branches:
      - production

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Pull development image, tag as production, and push
        working-directory: ./back
        run: |
          docker pull gastoooon/macave_backend:dev
          docker tag gastoooon/macave_backend:dev gastoooon/macave_backend:latest
          docker push gastoooon/macave_backend:latest

      - name: SSH into VPS and create .env
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > ~/Ma_Cave/back/.env
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> ~/Ma_Cave/back/.env
          echo "MYSQL_USER=${MYSQL_USER}" >> ~/Ma_Cave/back/.env
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> ~/Ma_Cave/back/.env
          echo "FLASK_ENV=production" >> ~/Ma_Cave/back/.env
          EOF

      - name: Deploy backend with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd  ~/Ma_Cave
          git stash
          git pull origin production
          cd back
          docker compose --env-file .env -f docker-compose-prod.yml up --build -d
          EOF