name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

        
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build and push backend image
        working-directory: ./back
        run: |
          docker compose -f docker-compose-prod.yml build api-flask
          docker tag gastoooon/macave_backend:latest docker.io/gastoooon/macave_backend:latest
          docker push docker.io/gastoooon/macave_backend:latest


